"""initial_schema

Revision ID: 74d841b0ece1
Revises: 
Create Date: 2026-08-06 10:40:21.356381
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '74d841b0ece1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('base_items',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=100), nullable=False),
    sa.Column('icon', sa.String(length=255), nullable=True),
    sa.Column('type', sa.Enum('WEAPON', 'ARMOR', 'HELMET', 'BOOTS', 'GLOVES', 'SHIELD', 'CONSUMABLE', 'MATERIAL', 'GEM', 'QUEST_ITEM', name='item_type'), nullable=False),
    sa.Column('rarity', sa.Enum('COMMON', 'UNCOMMON', 'RARE', 'EPIC', 'LEGENDARY', name='item_rarity'), nullable=False),
    sa.Column('equip_slot', sa.Enum('HEAD', 'BODY', 'WEAPON', 'SHIELD', 'GLOVES', 'BOOTS', name='equipment_slot'), nullable=True),
    sa.Column('class_restriction', sa.Enum('KNIGHT', 'ARCHER', 'NECROMANCER', name='character_class'), nullable=True),
    sa.Column('atk_bonus', sa.Integer(), nullable=False),
    sa.Column('def', sa.Integer(), nullable=False),
    sa.Column('speed_bonus', sa.Integer(), nullable=False),
    sa.Column('hp_bonus', sa.Integer(), nullable=False),
    sa.Column('level_requirement', sa.Integer(), nullable=False),
    sa.Column('stackable', sa.Boolean(), nullable=False),
    sa.Column('max_stack', sa.Integer(), nullable=False),
    sa.Column('buy_price', sa.Integer(), nullable=False),
    sa.Column('sell_price', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('buy_price >= 0'),
    sa.CheckConstraint('level_requirement >= 1'),
    sa.CheckConstraint('sell_price >= 0'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_base_items_name'), 'base_items', ['name'], unique=False)
    op.create_table('users',
    sa.Column('discord_id', sa.String(length=30), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('avatar_url', sa.String(length=255), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('consecutive_login_days', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_discord_id'), 'users', ['discord_id'], unique=True)
    op.create_table('zones',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('minimum_level_suggested', sa.Integer(), nullable=False),
    sa.Column('maximum_level_suggested', sa.Integer(), nullable=False),
    sa.Column('allow_pvp', sa.Boolean(), nullable=False),
    sa.Column('safe_zone', sa.Boolean(), nullable=False),
    sa.Column('respawn_x', sa.Integer(), nullable=False),
    sa.Column('respawn_y', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('characters',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('current_zone_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('class_type', sa.Enum('KNIGHT', 'ARCHER', 'NECROMANCER', name='character_class'), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('xp', sa.Integer(), nullable=False),
    sa.Column('gold', sa.Integer(), nullable=False),
    sa.Column('hp_current', sa.Integer(), nullable=False),
    sa.Column('hp_max', sa.Integer(), nullable=False),
    sa.Column('atk', sa.Integer(), nullable=False),
    sa.Column('def', sa.Integer(), nullable=False),
    sa.Column('speed', sa.Integer(), nullable=False),
    sa.Column('buff_current', sa.Integer(), nullable=False),
    sa.Column('appearance', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('position_x', sa.Integer(), nullable=False),
    sa.Column('position_y', sa.Integer(), nullable=False),
    sa.Column('tower_highest_floor', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['current_zone_id'], ['zones.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_characters_current_zone_id'), 'characters', ['current_zone_id'], unique=False)
    op.create_index(op.f('ix_characters_user_id'), 'characters', ['user_id'], unique=False)
    op.create_table('daily_logins',
    sa.Column('character_id', sa.UUID(), nullable=False),
    sa.Column('login_date', sa.Date(), nullable=False),
    sa.Column('streak_day', sa.Integer(), nullable=False),
    sa.Column('reward_claimed', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('character_id', 'login_date', name='uq_character_login_date')
    )
    op.create_index(op.f('ix_daily_logins_character_id'), 'daily_logins', ['character_id'], unique=False)
    op.create_table('guilds',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('leader_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['leader_id'], ['characters.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_guilds_name'), 'guilds', ['name'], unique=True)
    op.create_table('item_instances',
    sa.Column('item_base_id', sa.UUID(), nullable=False),
    sa.Column('owner_character_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('enchantment_level', sa.Integer(), nullable=False),
    sa.Column('enchantment_type', sa.Enum('NONE', 'FIRE', 'ICE', 'LIGHTNING', name='enchantment_type'), nullable=False),
    sa.Column('is_equipped', sa.Boolean(), nullable=False),
    sa.Column('slot_position', sa.Integer(), nullable=True),
    sa.Column('acquired_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('enchantment_level >= 0'),
    sa.CheckConstraint('quantity >= 1'),
    sa.ForeignKeyConstraint(['item_base_id'], ['base_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_character_id'], ['characters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_item_instances_item_base_id'), 'item_instances', ['item_base_id'], unique=False)
    op.create_index(op.f('ix_item_instances_owner_character_id'), 'item_instances', ['owner_character_id'], unique=False)
    op.create_table('pvp_records',
    sa.Column('killer_character_id', sa.UUID(), nullable=False),
    sa.Column('victim_character_id', sa.UUID(), nullable=False),
    sa.Column('zone_id', sa.UUID(), nullable=False),
    sa.Column('killed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['killer_character_id'], ['characters.id'], ),
    sa.ForeignKeyConstraint(['victim_character_id'], ['characters.id'], ),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pvp_records_killer_character_id'), 'pvp_records', ['killer_character_id'], unique=False)
    op.create_index(op.f('ix_pvp_records_victim_character_id'), 'pvp_records', ['victim_character_id'], unique=False)
    op.create_index(op.f('ix_pvp_records_zone_id'), 'pvp_records', ['zone_id'], unique=False)
    op.create_table('transactions',
    sa.Column('from_character_id', sa.UUID(), nullable=False),
    sa.Column('to_character_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('TRADE', 'GIFT', 'NPC', name='transaction_type'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'COMPLETED', 'CANCELLED', name='transaction_status'), nullable=False),
    sa.Column('gold_amount', sa.Integer(), nullable=False),
    sa.Column('items', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('gold_amount >= 0'),
    sa.ForeignKeyConstraint(['from_character_id'], ['characters.id'], ),
    sa.ForeignKeyConstraint(['to_character_id'], ['characters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_from_character_id'), 'transactions', ['from_character_id'], unique=False)
    op.create_index(op.f('ix_transactions_to_character_id'), 'transactions', ['to_character_id'], unique=False)
    op.create_table('guild_members',
    sa.Column('guild_id', sa.UUID(), nullable=False),
    sa.Column('character_id', sa.UUID(), nullable=False),
    sa.Column('rank', sa.Enum('LEADER', 'OFFICER', 'MEMBER', name='guild_rank'), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['guild_id'], ['guilds.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('guild_id', 'character_id')
    )
    op.create_table('guild_territories',
    sa.Column('guild_id', sa.UUID(), nullable=False),
    sa.Column('tower_floor', sa.Integer(), nullable=False),
    sa.Column('conquered_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('gold_accumulated', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['guild_id'], ['guilds.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('guild_id', 'tower_floor')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('guild_territories')
    op.drop_table('guild_members')
    op.drop_index(op.f('ix_transactions_to_character_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_from_character_id'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_pvp_records_zone_id'), table_name='pvp_records')
    op.drop_index(op.f('ix_pvp_records_victim_character_id'), table_name='pvp_records')
    op.drop_index(op.f('ix_pvp_records_killer_character_id'), table_name='pvp_records')
    op.drop_table('pvp_records')
    op.drop_index(op.f('ix_item_instances_owner_character_id'), table_name='item_instances')
    op.drop_index(op.f('ix_item_instances_item_base_id'), table_name='item_instances')
    op.drop_table('item_instances')
    op.drop_index(op.f('ix_guilds_name'), table_name='guilds')
    op.drop_table('guilds')
    op.drop_index(op.f('ix_daily_logins_character_id'), table_name='daily_logins')
    op.drop_table('daily_logins')
    op.drop_index(op.f('ix_characters_user_id'), table_name='characters')
    op.drop_index(op.f('ix_characters_current_zone_id'), table_name='characters')
    op.drop_table('characters')
    op.drop_table('zones')
    op.drop_index(op.f('ix_users_discord_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_base_items_name'), table_name='base_items')
    op.drop_table('base_items')
    # ### end Alembic commands ###
